version: "3.9"

services:
  backend:
    build: .
    container_name: img-bg
    volumes:
      - .:/app  
    ports:
      - "7000:7000"
    networks:
      - mynet

networks:
  mynet:
    driver: bridge